name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # 1. Download the latest project code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install OpenShift CLI
      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      # 3. Create Docker image name using the GitHub commit SHA
      - name: Set image name
        run: |
          echo "IMAGE=apar202511/lemp-containers-backend:${GITHUB_SHA}" >> $GITHUB_ENV

      # 4. Build the backend Docker image
      - name: Build Docker image
        run: |
          docker build \
            -f backend/Dockerfile \
            -t "$IMAGE" \
            .

      # 5. Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      # 6. Push the image to Docker Hub
      - name: Push Docker image
        run: |
          docker push "$IMAGE"

      # 7. Build the frontend Docker image
      - name: Build frontend image
        run: |
          docker build \
            -f frontend/Dockerfile \
            -t "apar202511/lemp-containers-frontend:${GITHUB_SHA}" \
            frontend

      # 8. Push the frontend image to Docker Hub
      - name: Push frontend image
        run: |
          docker push "apar202511/lemp-containers-frontend:${GITHUB_SHA}"

      # 9. Login to Rahti
      - name: Login to Rahti
        run: |
          oc login \
            --server="${{ secrets.RAHTI_SERVER }}" \
            --token="${{ secrets.RAHTI_TOKEN }}"

      # 10. Select the Rahti project
      - name: Select Rahti project
        run: |
          oc project aps

      # 11. Update the frontend deployment
      - name: Update frontend deployment
        run: |
          oc set image deployment/assignment-2 \
            assignment-2="apar202511/lemp-containers-frontend:${GITHUB_SHA}"

      # 12. Wait until the frontend deployment is ready
      - name: Wait for frontend deployment
        run: |
          oc rollout status deployment/assignment-2    

      # 13. Update the backend deployment
      - name: Update backend deployment
        run: |
          oc set image deployment/backend \
            backend="$IMAGE"

      # 14. Wait until the new deployment is ready
      - name: Wait for deployment
        run: |
          oc rollout status deployment/backend

      # 15. Check running pods
      - name: Check pods
        run: |
          oc get pods

      # 16. Check backend deployment
      - name: Check deployment
        run: |
          oc get deployment backend

      # 17. Check services
      - name: Check services
        run: |
          oc get services

      # 18. Check routes
      - name: Check routes
        run: |
          oc get routes